#!/usr/bin/env sh
# SPDX-License-Identifier: LGPL-2.1-or-later
# test (some) efivar thread safety
#
# Copyright Jonathan Marler and contributors

if [ "$#" -ne 1 ] ; then
	echo "Usage: ${0} <path to thread test>"
	exit 1
fi

rm -rf scratch
mkdir scratch

set -eu

TESTERPATH="$1"
EFIVARFS_PATH=$(realpath scratch)/
LIBEFIVAR_OPS=efivarfs
export EFIVARFS_PATH LIBEFIVAR_OPS

test() {
	echo -n "testing $1 thread..."
	"$TESTERPATH" -t "$1"
}

test 1
test 2
test 4
test 64
